--- #YAML:1.0
name: Spoon-Template-Mason
version: 0.02
author:
  - Dave Rolsky <autarch@urth.org>
abstract: A Spoon template module that uses Mason
license: perl
requires:
  Spoon: 0.12
provides:
  Spoon::Template::Mason:
    file: lib/Spoon/Template/Mason.pm
    version: 0.02
generated_by: Module::Build version 0.23
