--- #YAML:1.0
name: Spoon-Template-Mason
version: 0.04
author:
  - Dave Rolsky <autarch@urth.org>
abstract: A Spoon template module that uses Mason
license: perl
requires:
  HTML::Mason: 1.1
  Spoon: 0.12
provides:
  Spoon::Template::Mason:
    file: lib/Spoon/Template/Mason.pm
    version: 0.04
generated_by: Module::Build version 0.25
